# Schema for the configuration files of the Fer departments module.
fer_departments.settings:
  type: config_object
  label: 'Fer departments settings'
  mapping:
    example:
      type: string
      label: 'Example'
